### ISSUE TITLE
AttributeError: 'module' object has no attribute 'select'

### ISSUE THREAD

**Issue by aht** [Enny1991/PLSTM#10]
Looks like this has gone out of the window in tensorflow 1.0, https://github.com/tensorflow/tensorflow/issues/6899

**Comment by Enny1991** [comment]
Yeah you have to use *v1 for TF 1.0 there the implementation has been changed from `tf.select` to `tf.where`.

**Comment by aht** [comment]
Thanks @Enny1991 I was confused whether the v1 applies to the PLSTM code or TF. It works!
