### ISSUE TITLE
multiPLSTM and RNN doesn't parameterize the cell correctly

### ISSUE THREAD

**Issue by aht** [Enny1991/PLSTM#8]
multiPLSTM and RNN doesn't parameterize the cell correctly. 

multiPLSTM basically hardcode to cell = PhasedLSTMCell(units_p_layer, use_peepholes=True, state_is_tuple=True) so the params such as `r_on`, `tau_init` cannot be passed in.

Also in simplePhasedLSTM.py, the RNN function always creates PLSTM cell, not LSTM or GRU. This means that the run flag is not used flags.DEFINE_string("unit", "PLSTM", "Can be PSLTM, LSTM, GRU").

I'm happy to contribute a fix.

**Comment by Enny1991** [comment]
@aht 
Thanks for the tip. Now the function accepts a list of cells such that you can parameterize them.
```python
    outputs = multiPLSTM(cells, inputs, lens, n_input, initial_states)
```

I deleted the flags for the units. For a unit test it does not make sense to have them. The code shows only PLSTM.

+Enea

**Comment by Enny1991** [comment]
solved, I close it
